# Generated by Django 4.1 on 2022-11-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_tasksuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasksuser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
