# Generated by Django 4.1 on 2022-11-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_tasksuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasksuser",
            name="name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="tasksuser",
            name="occupation",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
