# Generated by Django 4.1 on 2022-12-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Choose your gender"),
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Custom", "Custom"),
                    ("Prefer not to say", "Prefer not to say"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
