# Generated by Django 4.1 on 2022-11-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_priority",
            field=models.BooleanField(default=False),
        ),
    ]
