# Generated by Django 4.1 on 2021-08-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_is_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-updated"]},
        ),
    ]
